### ISSUE TITLE
When .NET 7 is installed the app crashes with razor build errors

### ISSUE THREAD

**Issue by maryamariyan** [Azure-Samples/Orleans-Cluster-on-Azure-App-Service#2]
The app compiles with build error in razor file cart.razor

<img width="527" alt="image" src="https://user-images.githubusercontent.com/5897654/181097243-2b8f0430-f995-462c-ab8b-96aa9a513f07.png">

<img width="614" alt="image" src="https://user-images.githubusercontent.com/5897654/181097371-afec5e3e-99a9-463d-88a2-71a0748c23e9.png">

workaround seems to be running the script below in the csproj directory:

> dotnet new globaljson --sdk-version 6.0.302

Might be helpful to include this script into the docs on this repo.

cc @bradygaster @IEvangelist

**Comment by IEvangelist** [comment]
Addressed in edd8b9f
